#!/bin/bash
cd /home/pi/Q100/q100receiver-v3/_longmynd/
# /home/pi/Q100/q100receiver-v3/_longmynd/longmynd -S 0.6 741500 1500 > /dev/null 2>&1 &
/home/pi/Q100/q100receiver-v3/_longmynd/longmynd -S 0.6 741500 1500 &